shipit update

diff --git a/bin/shipit b/bin/shipit
--- a/bin/shipit
+++ b/bin/shipit
@@ -2,7 +2,7 @@
 
 #
 # Minimalistic SSH deployment.
-# 
+#
 # Author: Artem Sapegin, sapegin.me
 # License: MIT
 #
@@ -11,12 +11,15 @@
 # http://gleero.com/all/remote-ssh/
 #
 
-
-VERSION="0.1.0"
-CONFIG=./.shipit
+PROGRAM=$(basename "$0")
+VERSION="0.3.0"
+CONFIG_DIR=$(pwd)
+CONFIG_NAME=.shipit
+CONFIG=
 TARGET=deploy
 SSH_HOST=
 SSH_PATH=
+VERBOSE=
 
 # Common stuff
 RED="$(tput setaf 1)"
@@ -33,19 +36,22 @@ function error() { echo -e "$UNDERLINE$RED$1$NOCOLOR\n"; }
 usage() {
 	version
 	echo
-	echo "Usage: `basename $0` [command|option]"
-	echo
-	echo "Options:"
-	echo
-	echo "    -V, --version    Print program version"
-	echo "    -h, --help       Print help (this screen)"
+	echo "Usage: $PROGRAM [option] <command>"
 	echo
 	echo "Commands:"
 	echo
-	echo "    <target>         Executes <target> target on remote host (run shipit to execute 'deploy' target)"
-	echo "    list             Print list of available targets"
-	echo "    console          Open an SSH session on remote host"
-	echo "    exec <cmd>       Execute <cmd> on remote host"
+	echo "    <target>                 Execute <target> target on remote host"
+	echo "    list         ls          Print list of available targets"
+	echo "    console      shell, ssh  Open an SSH session on the remote host"
+	echo "    exec <cmd>   run         Execute <cmd> on the remote host"
+	echo "    copy <file>  cp          Copy <files> to the remote host"
+	echo "    --version    -V          Print program version"
+	echo "    --help       -h          Print help (this screen)"
+	echo
+	echo "Options:"
+	echo
+	echo "    -c, --config             Config file name (default: .shipit)"
+	echo "    -v, --verbose            Enable verbose mode for SSH"
 	echo
 }
 
@@ -59,7 +65,18 @@ abort() {
 # Print version number
 version() {
 	echo
-	echo "`basename $0` v$VERSION"
+	echo "$PROGRAM v$VERSION"
+}
+
+# Enable verbose mode
+set_verbose() {
+	VERBOSE="1"
+}
+
+# Set config file name
+set_config_file() {
+	test -z "$1" && abort 'File name is required for --config/-c option.'
+	CONFIG_NAME="$1"
 }
 
 # Print squirrel
@@ -72,20 +89,38 @@ squirrel() {
 	echo "$NOCOLOR"
 }
 
+# Traverse upwards until we find the config file
+find_config() {
+	while [ ! -f "$CONFIG_DIR/$CONFIG_NAME" ]; do
+		if [ "$CONFIG_DIR" == "/" ]; then
+			break;
+		fi
+
+		CONFIG_DIR=$(dirname "$CONFIG_DIR")
+	done
+
+	if [ -f "$CONFIG_DIR/$CONFIG_NAME" ]; then
+		CONFIG="$CONFIG_DIR/$CONFIG_NAME"
+	fi
+}
+
 # Read and validate config file
 read_config() {
+	local config
+
+	find_config
 	# Check config file existance
-	test -f $CONFIG || abort "Config file $CONFIG not found." 
+	test -f "$CONFIG" || abort "Config file $CONFIG_NAME not found."
 
 	# Read and eval first section
-	local config=`awk '/^/ {print; exit}' RS= $CONFIG`
+	config=$(awk '/^/ {print; exit}' RS= $CONFIG)
 	eval $config
 
 	# Check required params
 	test -z "$host" && incomplete_config 'host'
 	test -z "$path" && incomplete_config 'path'
 	test -z "$host" || test -z "$path" && exit 1
-	
+
 	# Expose params
 	SSH_HOST=$host
 	SSH_PATH=$path
@@ -98,6 +133,9 @@ incomplete_config() {
 
 # Deploy specified target
 deploy() {
+	local local_script
+	local remote_script
+
 	read_config
 
 	# Check target existance
@@ -107,22 +145,22 @@ deploy() {
 	header "Shipping $TARGET..."
 
 	# Read local script
-	local local_script=`awk "/^\[$TARGET:local\]/ {print; exit}" RS= $CONFIG | sed 1d`
+	local_script=$(awk "/^\[$TARGET:local\]/ {print; exit}" RS= $CONFIG | sed 1d)
 	if [ -n "$local_script" ]; then
 		header "Running local script..."
 		run_local "$local_script"
 		if [ $? -ne 0 ]; then
-			abort "Deploy wasn’t successful: local script failed."	
+			abort "Deploy wasn’t successful: local script failed."
 		fi
 	fi
 
 	# Read remote script
-	local remote_script=`awk "/^\[$TARGET\]/ {print; exit}" RS= $CONFIG | sed 1d`
+	remote_script=$(awk "/^\[$TARGET\]/ {print; exit}" RS= $CONFIG | sed 1d)
 	if [ -n "$remote_script" ]; then
 		header "Running remote script at $SSH_HOST..."
 		run_remote "$remote_script"
 		if [ $? -ne 0 ]; then
-			abort "Deploy wasn’t successful: remote script failed."	
+			abort "Deploy wasn’t successful: remote script failed."
 		fi
 	fi
 
@@ -150,7 +188,14 @@ run_remote() {
 		cd \"$SSH_PATH\"
 		$1
 	"""
-	ssh -A $2 "$SSH_HOST" "$script"
+
+	local verbose=
+
+	if [ -n "$VERBOSE" ]; then
+		verbose="-v"
+	fi
+
+	ssh $verbose -A $2 "$SSH_HOST" "$script"
 }
 
 # Run local script
@@ -178,14 +223,14 @@ open_console() {
 # Execute command via SSH
 exec_command() {
 	read_config
-	header "Executing $@ on $SSH_HOST..."
-	run_remote $@
+	header "Executing $* on $SSH_HOST..."
+	run_remote "$*"
 }
 
 # Copy local file to remote host
 copy_to_remote() {
 	read_config
-	test -f "$1" || abort "Local file $1 not found." 
+	test -f "$1" || abort "Local file $1 not found."
 	header "Copying $1 to $SSH_HOST..."
 	scp "$1" "$SSH_HOST:$SSH_PATH/$1"
 }
@@ -194,6 +239,16 @@ copy_to_remote() {
 ########################################################################################################################
 
 # Parse CLI arguments
+
+# Options
+for arg in "$@"; do
+	case "$arg" in
+		-v|--verbose) set_verbose; shift ;;
+		-c|--config) set_config_file "$2"; shift; shift ;;
+	esac
+done
+
+# Commands
 arg=$1; shift
 if [ -n "$arg" ]; then
 	case $arg in
